name: "Validate the code"

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install pnpm
        run: corepack enable

      - uses: actions/setup-node@v6
        with:
          cache-dependency-path: pnpm-lock.yaml
          cache: "pnpm"
          node-version-file: .nvmrc

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate typed routes
        run: pnpm generate-typed-routes

      - name: Check types
        run: pnpm check-types

      - name: Check formatting
        run: pnpm check-formatting

      - name: Check for unused files and dependencies
        run: pnpm check-unused

      - name: Check linting
        run: pnpm check-lint
